general:
  seed: 2021
  save_model: true
  save_model_dir: "ignore/models"
  save_model_name: "adult_experiment"
  tensorboard: true
  tensorboard_dir: "ignore/runs/adult"

# Specify training parameters
training:

  num_iterations: 500
  num_episodes_per_iteration: 10
  patience: 10
  early_stopping_accuracy: 0.75

  mcts:
    name: "generalized_alphanpi.mcts.mcts_multiple_args.MCTSMultipleArgs"
    configuration_parameters:
      exploration: true
      number_of_simulations: 10
      dir_epsilon: 0.03
      dir_noise: 0.35
      level_closeness_coeff: 1.0
      level_0_penalty: 1.0
      action_cost_coeff: 1.0
      action_duplicate_cost: 1.0
      qvalue_temperature: 1.0
      temperature: 1.3
      c_puct: 0.5
      gamma: 0.8

  trainer:
    batch_size: 50

  curriculum_scheduler:
    next_action_accuracy: 0.97
    moving_average: 0.99

  replay_buffer:
    size: 200
    sampling_correct_probability: 0.8

# Environment of this experiment
environment:
  name: "synthetizer.adult_score.environment.AdultEnvironment"
  configuration_parameters:
    sample_from_errors_prob: 0.35
    classifier: "models/adult_classifier_09122021-153755.pth"
    encoder: "models/adult_classifier_encoder_09122021-153755.pth"
    scaler: "models/adult_classifier_scaling_09122021-153755.pth"

  # Encoder for the environment of this experiment
  encoder:
    name: "synthetizer.adult_score.environment.AdultEnvEncoder"
    configuration_parameters:
      encoding_dim: 50

# Policy used for this experiment
policy:
  name: "generalized_alphanpi.agents.multiple_args_policy.MultipleArgsPolicy"
  hidden_size: 50
  embedding_dim: 100
  encoding_dim: 50 # This needs to be equal to the encoder embedding_dim
  #pretrained_model: "ignore/models/adult_experiment-2021_12_15-11_43_11.model"

validation:
  dataset_name: "adult"
  iterations: 100
  environment:
    configuration_parameters:
      dataset: "data/adult_score/test.csv"
      sample_env: False
  save_results: "ignore"
  save_results_name: "results"
