general:
  seed: 2021
  save_model: true
  save_model_dir: "ignore/models"
  save_model_name: "german_experiment"
  tensorboard: true
  tensorboard_dir: "ignore/runs/german"

dataloader:
  sample_errors: 0.1
  configuration_parameters:
    dataset: "data/german_credit/train.csv"
    bad_class_value: "bad"
    target_column: "risk"
    predicted_column: "predicted"

# Specify training parameters
training:

  num_iterations: 200
  num_episodes_per_iteration: 10
  patience: 10
  early_stopping_accuracy: 0.90

  mcts:
    name: "rl_mcts.core.mcts.MCTS"
    configuration_parameters:
      exploration: true
      number_of_simulations: 10
      dir_epsilon: 0.3
      dir_noise: 0.35
      level_closeness_coeff: 1.0
      level_0_penalty: 1.0
      action_cost_coeff: 1.0
      action_duplicate_cost: 1.0
      qvalue_temperature: 1.0
      temperature: 1.3
      c_puct: 0.5
      gamma: 0.5

  trainer:
    batch_size: 50

  curriculum_statistics:
    next_action_accuracy: 0.97
    moving_average: 0.99

  replay_buffer:
    size: 200
    sampling_correct_probability: 0.8

# Environment of this experiment
environment:
  name: "synthetizer.german.environment.GermanEnvironment"
  configuration_parameters:
    classifier: "models/german_classifier_09122021-164545.pth"
    encoder: "models/german_classifier_encoder_09122021-164545.pth"
    scaler: "models/german_classifier_scaling_09122021-164545.pth"

  # Encoder for the environment of this experiment
  encoder:
    name: "synthetizer.german.environment.GermanEnvEncoder"
    configuration_parameters:
      encoding_dim: 50

# Policy used for this experiment
policy:
  name: "rl_mcts.core.agents.Policy"
  hidden_size: 50
  encoding_dim: 50 # This needs to be equal to the encoder embedding_dim

validation:
  dataset_name: "german"
  iterations: 34 # These are the total examples classified unfavorably by the black-box classifier
    
  dataloader:
    configuration_parameters:
      dataset: "data/german_credit/test.csv"
      bad_class_value: "bad"
      target_column: "risk"
      predicted_column: "predicted"

  mcts:
    name: "rl_mcts.core.mcts.MCTS"
    configuration_parameters:
      exploration: false
      number_of_simulations: 5
      dir_epsilon: 0.3
      dir_noise: 0.35
      level_closeness_coeff: 1.0
      level_0_penalty: 1.0
      action_cost_coeff: 1.0
      action_duplicate_cost: 1.0
      qvalue_temperature: 1.0
      temperature: 1.3
      c_puct: 0.5
      gamma: 0.5

  save_results: "ignore"
  save_results_name: "results"
