general:
  seed: 2021
  save_model: true
  save_model_dir: "ignore/models"
  save_model_name: "synthetic_experiment"
  tensorboard: true
  tensorboard_dir: "ignore/runs/syn"

dataloader:
  sample_errors: 0.1
  configuration_parameters:
    dataset: "data/synthetic/train.csv"
    bad_class_value: "bad"
    target_column: "loan"
    predicted_column: "loan"

# Specify training parameters
training:

  num_iterations: 1000
  num_episodes_per_iteration: 15
  patience: 10
  early_stopping_accuracy: 0.90

  mcts:
    name: "rl_mcts.core.mcts.MCTS"
    configuration_parameters:
      number_of_simulations: 10
      dir_epsilon: 0.3
      dir_noise: 0.35
      level_closeness_coeff: 1.0
      level_0_penalty: 1.0
      action_cost_coeff: 2.0
      action_duplicate_cost: 1.0
      qvalue_temperature: 1.0
      temperature: 1.3
      c_puct: 0.5
      gamma: 0.97

  trainer:
    batch_size: 50

  curriculum_statistics:
    next_action_accuracy: 0.97
    moving_average: 0.99

  replay_buffer:
    size: 200
    sampling_correct_probability: 0.8

# Environment of this experiment
environment:
  name: "synthetizer.synthetic.environment.SynEnvironmentDeter"
  configuration_parameters:
    encoder: "models/synthetic_classifier_encoder_02122021-145139.pth"
    scaler: "models/synthetic_classifier_scaling_02122021-145139.pth"

  # Encoder for the environment of this experiment
  encoder:
    name: "synthetizer.synthetic.environment.SynEnvEncoder"
    configuration_parameters:
      encoding_dim: 50

# Policy used for this experiment
policy:
  name: "rl_mcts.core.agents.Policy"
  hidden_size: 50
  embedding_dim: 100
  encoding_dim: 50 # This needs to be equal to the encoder embedding_dim
  #pretrained_model: "ignore/models/synthetic_deterministic_experiment-2021_12_17-14_52_32.model"

validation:
  dataset_name: "syn"
  iterations: 100

  mcts:
    name: "rl_mcts.core.mcts.MCTS"
    configuration_parameters:
      number_of_simulations: 5
      dir_epsilon: 0.03
      dir_noise: 0.35
      level_closeness_coeff: 1.0
      level_0_penalty: 1.0
      action_cost_coeff: 2.0
      action_duplicate_cost: 1.0
      qvalue_temperature: 1.0
      temperature: 1.3
      c_puct: 0.5
      gamma: 0.97
      exploration: False
    
  dataloader:
    configuration_parameters:
      dataset: "data/synthetic/test.csv"
      bad_class_value: "bad"
      target_column: "loan"
      predicted_column: "loan"
  
  save_results: "ignore"
  save_results_name: "results"
